### PR TITLE
making heatcanvas work with modern leaflet version

### PR DESCRIPTION
**Pull request by se-ti**
Hi! 
I enjoyed using ancient version your plugin with ancient LeafLet version (0.7) for many years. 
But when i tried to migrate to actual versions of both plugin and Leaflet, it turned out they fail with several errors.

I spent some time debugging, and made it work.

Hope, this fixes issue #34, and probably even #27, and #32

Serge.

### CODE REVIEW

**Comment by se-ti** [comment]
Any objections?

**Comment by sunng87** [comment]
Sorry for late. I will take a look later today and come back to you. Thank you very much!

**Comment by se-ti** [comment]
Ok :)
I'm ready to commit and pull set of changes dealing canvas resizing (and toggling fullscreen mode) and several speed optimizations.
These optimizations led to 10-12 times speed up for my case: ~15K points and high peaks, flooding almost all screen at common zoom levels.

But let's start with these simple changes.

**Comment by sunng87** [comment]
That sounds neat! I'm looking forward to your new patch and really interested in your optimization.

**Review by sunng87 — APPROVED** [review]

**Pull request merged**
